// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab_3;

#nullable disable

namespace lab_3.Migrations
{
    [DbContext(typeof(MachineContext))]
    [Migration("20220928143807_Init3")]
    partial class Init3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("lab_3.Drink", b =>
                {
                    b.Property<int>("DrinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name_Drink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Portion_Drink")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price_Drink")
                        .HasColumnType("INTEGER");

                    b.HasKey("DrinkId");

                    b.ToTable("Drinks");
                });

            modelBuilder.Entity("lab_3.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drink_1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drink_2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drink_3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Drink_4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Machine_components")
                        .HasColumnType("INTEGER");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("lab_3.Machine_component", b =>
                {
                    b.Property<int>("Machine_componentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckPaper")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cups")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sugar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Machine_componentId");

                    b.ToTable("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
